[package]
name = "jace"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
mlua = { version = "0.10", features = ["luajit52", "vendored"] }
backtrace-on-stack-overflow = "0.3.0"
regex = "1.11.1"
