[package]
name = "jace"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
mlua = { version = "0.10", features = ["luajit52", "vendored"] }
clap = { version = "4.5.28", features = ["derive"] }
miette = { version = "7.5.0", features = ["fancy"] }
