[package]
name = "jace"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
mlua = { version = "0.10", features = ["luajit52", "vendored"] }
backtrace-on-stack-overflow = "0.3.0"
codespan-reporting = "0.11.1"
clap = { version = "4.5.28", features = ["derive"] }
